[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd web_app && npm install && npm run build && cd .."
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"