[phases.setup]
nixPkgs = ["python310", "nodejs_18"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt",
    "cd web_app && npm install && npm run build && cd .."
]

[start]
cmd = "python3 -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"