[phases.setup]
nixPkgs = ["python310", "nodejs_18"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    "cd web_app && npm install && npm run build && cd .."
]

[start]
cmd = ". /opt/venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"