[phases.setup]
nixPkgs = ["python310", "nodejs_18", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd web_app && npm install && npm run build && cd .."
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"